# Generated by Django 4.2.5 on 2023-10-17 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learnit', '0002_myreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
