# Generated by Django 4.2.5 on 2023-11-17 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_alter_proof_student'),
        ('Learnit', '0006_rename_user_myreview_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myreview',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student.student'),
        ),
    ]
