# Generated by Django 4.2.5 on 2023-10-29 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_mycourse_coursename_remove_mycourse_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='courseName',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile Development', 'Mobile Development'), ('Python Development', 'Python Development'), ('Data Analysis', 'Data Analysis'), ('Devopn Tools', 'Devopn Tools'), ('UI/UX Design', 'UI/UX Design'), ('UI/UX Design', 'UI/UX Design')], max_length=500),
        ),
        migrations.RemoveField(
            model_name='mycourse',
            name='user',
        ),
        migrations.AddField(
            model_name='mycourse',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
            preserve_default=False,
        ),
    ]
