# Generated by Django 4.2.5 on 2023-10-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_mycourse_coursename_remove_mycourse_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='courseName',
            field=models.CharField(blank=True, choices=[('Web Development', 'Web Development'), ('Mobile Development', 'Mobile Development'), ('Python Development', 'Python Development'), ('Data Analysis', 'Data Analysis'), ('Devopn Tools', 'Devopn Tools'), ('UI/UX Design', 'UI/UX Design'), ('UI/UX Design', 'UI/UX Design')], max_length=500, null=True),
        ),
    ]
