# Generated by Django 4.2.5 on 2023-10-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_mycourse_coursename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycourse',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='courseName',
            field=models.ManyToManyField(to='student.mycourse'),
        ),
    ]
