# Generated by Django 4.2.5 on 2023-10-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_student_coursename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycourse',
            old_name='courseName',
            new_name='coursename',
        ),
    ]
