# Generated by Django 4.2.5 on 2023-10-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_rename_coursename_mycourse_coursename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='coursename',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
