# Generated by Django 4.2.5 on 2023-10-31 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_mycourse_coursename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='courseName',
            new_name='course_names',
        ),
    ]
