# Generated by Django 4.2.5 on 2023-10-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_remove_student_course_names_student_studentcourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycourse',
            old_name='coursename',
            new_name='course1',
        ),
        migrations.AddField(
            model_name='mycourse',
            name='course2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mycourse',
            name='course3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mycourse',
            name='course4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mycourse',
            name='course5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mycourse',
            name='course6',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mycourse',
            name='course7',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
