# Generated by Django 4.2.5 on 2023-11-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_rename_coursename_mycourse_course1_mycourse_course2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycourse',
            old_name='course1',
            new_name='CyberSecurity',
        ),
        migrations.RenameField(
            model_name='mycourse',
            old_name='course2',
            new_name='DataAnalysis',
        ),
        migrations.RenameField(
            model_name='mycourse',
            old_name='course3',
            new_name='DevopTools',
        ),
        migrations.RenameField(
            model_name='mycourse',
            old_name='course4',
            new_name='MobileDevelopment',
        ),
        migrations.RenameField(
            model_name='mycourse',
            old_name='course5',
            new_name='PythonDevelopment',
        ),
        migrations.RenameField(
            model_name='mycourse',
            old_name='course6',
            new_name='UI_UXDesign',
        ),
        migrations.RenameField(
            model_name='mycourse',
            old_name='course7',
            new_name='WebDevelopment',
        ),
    ]
