# Generated by Django 4.2.5 on 2023-11-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_rename_course1_mycourse_cybersecurity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycourse',
            old_name='CyberSecurity',
            new_name='coursename',
        ),
        migrations.RemoveField(
            model_name='mycourse',
            name='DataAnalysis',
        ),
        migrations.RemoveField(
            model_name='mycourse',
            name='DevopTools',
        ),
        migrations.RemoveField(
            model_name='mycourse',
            name='MobileDevelopment',
        ),
        migrations.RemoveField(
            model_name='mycourse',
            name='PythonDevelopment',
        ),
        migrations.RemoveField(
            model_name='mycourse',
            name='UI_UXDesign',
        ),
        migrations.RemoveField(
            model_name='mycourse',
            name='WebDevelopment',
        ),
    ]
