# Generated by Django 4.2.5 on 2023-11-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_rename_cybersecurity_mycourse_coursename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='paymentProof',
            field=models.ManyToManyField(to='student.proof'),
        ),
    ]
