# Generated by Django 4.2.5 on 2023-11-04 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_proof_student_paymentproof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='paymentProof',
        ),
        migrations.AddField(
            model_name='proof',
            name='student',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
            preserve_default=False,
        ),
    ]
