# Generated by Django 4.2.5 on 2023-11-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_remove_student_paymentproof_proof_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='uploadDateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
