# Generated by Django 4.2.5 on 2023-11-05 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_alter_proof_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
