# Generated by Django 4.2.5 on 2023-11-19 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_alter_proof_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student.student'),
        ),
    ]
